[mypy]
python_version = 3.11
strict = false
disallow_untyped_defs = true
warn_return_any = false
plugins = sqlalchemy_stubs.mypy_plugin

# Не проверять миграции Alembic — они не для типизации
[mypy-alembic.*]
follow_imports = skip
ignore_missing_imports = true

# Тесты тоже можно не проверять строго
[mypy-tests.*]
follow_imports = skip
ignore_missing_imports = true

# Если есть фиксы/примеры — тоже можно пропустить
[mypy-examples.*]
follow_imports = skip
ignore_missing_imports = true
