"""add surname

Revision ID: 4bec28cb6fce
Revises: 1cc635cebe29
Create Date: 2026-09-03 12:14:46.682290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bec28cb6fce'
down_revision: Union[str, Sequence[str], None] = '1cc635cebe29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
