"""add partonomic

Revision ID: c5c33560bf82
Revises: 4bec28cb6fce
Create Date: 2026-09-03 12:25:33.790067

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5c33560bf82"
down_revision: Union[str, Sequence[str], None] = "72c490aa4425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("patronomic", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "patronomic")
    # ### end Alembic commands ###
